"""Database operations module"""

from .connection import get_connection, close_connection, return_connection, close_all_connections, init_pool, test_connection
from .operations import (
    save_chapter,
    save_raw_event,
    chapter_exists,
    get_last_scraped_chapter,
    save_chapter_metadata,
    save_chapters_batch,
    get_chapter_url,
    get_total_chapters,
    save_raw_events_batch,
)
from .wiki_operations import (
    save_wiki_character,
    save_wiki_characters_batch,
    get_wiki_character_count,
    get_all_wiki_character_names,
    get_wiki_character_with_aliases,
    save_wiki_skill,
    save_wiki_skills_batch,
    get_wiki_skill_count,
    get_all_wiki_skills,
    is_fake_skill,
    save_wiki_spell,
    save_wiki_spells_batch,
    get_wiki_spell_count,
    get_all_wiki_spells,
    save_wiki_class,
    save_wiki_classes_batch,
    get_wiki_class_count,
    get_all_wiki_classes,
    is_fake_class,
    update_wiki_scrape_state,
    get_wiki_scrape_state,
    get_all_wiki_scrape_states,
)

__all__ = [
    "get_connection",
    "close_connection",
    "return_connection",
    "close_all_connections",
    "init_pool",
    "test_connection",
    "save_chapter",
    "save_raw_event",
    "chapter_exists",
    "get_last_scraped_chapter",
    "save_chapter_metadata",
    "save_chapters_batch",
    "get_chapter_url",
    "get_total_chapters",
    "save_raw_events_batch",
    # Wiki operations
    "save_wiki_character",
    "save_wiki_characters_batch",
    "get_wiki_character_count",
    "get_all_wiki_character_names",
    "get_wiki_character_with_aliases",
    "save_wiki_skill",
    "save_wiki_skills_batch",
    "get_wiki_skill_count",
    "get_all_wiki_skills",
    "is_fake_skill",
    "save_wiki_spell",
    "save_wiki_spells_batch",
    "get_wiki_spell_count",
    "get_all_wiki_spells",
    "save_wiki_class",
    "save_wiki_classes_batch",
    "get_wiki_class_count",
    "get_all_wiki_classes",
    "is_fake_class",
    "update_wiki_scrape_state",
    "get_wiki_scrape_state",
    "get_all_wiki_scrape_states",
]
